name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.inputs.environment == 'production' }}
    
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: consilio.cc
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/samuel/consilio
            docker-compose pull
            docker-compose up -d
            docker system prune -af 