name: Build and Push Docker Image

on:
  # Automatically trigger on push to main branch
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/docker-build-push.yml'
  
  # Keep manual trigger option
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set tag based on trigger type
      - name: Set tag for auto trigger
        if: github.event_name == 'push'
        run: |
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "DEPLOY_ENV=production" >> $GITHUB_ENV

      # Set tag based on manual input
      - name: Set tag for manual trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          echo "DEPLOY_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      # Prepare customization files
      - name: Prepare customization files
        run: |
          mkdir -p docker/customizations/components/global_header/left_controls/product_menu/product_branding_team_edition/
          cp -r webapp-src/components/global_header/left_controls/product_menu/product_branding_team_edition/* docker/customizations/components/global_header/left_controls/product_menu/product_branding_team_edition/

      - name: Build and push Consilio image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/consilio:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/consilio:${{ github.sha }}
          cache-from: type=gha 